name: Validación de ESLint

# Se dispara en cada push y pull request sobre la rama 'main'
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      # Paso 1: Clona el repositorio
      - name: Checkout repository
        uses: actions/checkout@v3

      # Paso 2: Configura el entorno de Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "22"

      # Paso 3: Instala pnpm
      - name: Install pnpm package manager
        uses: pnpm/action-setup@v4
        with:
          version: 10

      # Paso 3: Instala las dependencias del proyecto
      - name: Install dependencies
        run: pnpm install --dev

      # Paso 4: Ejecuta ESLint usando el comando definido en package.json
      - name: Run ESLint
        run: pnpm lint